### ISSUE TITLE
isBoolean()

### ISSUE THREAD

**Issue by spotshare-nick** [carlitux/koa-async-validator#1]
Please add isBoolean() to the code.

```
Validator.prototype.isBoolean = function(tip) {
    if (this.goOn && (!isString(this.value) ||!v.isBoolean(this.value))) {
        this.addError(tip || this.key + " is not boolean.");
    }
    return this;
};
```

**Comment by carlitux** [comment]
@nblasgen node validator has that option https://github.com/chriso/validator.js you can use it, no need to add code.

**Comment by spotshare-nick** [comment]
`[ERROR] app - [TypeError: ctx.checkBody(...).get(...).notEmpty(...).isBoolean is not a function]`

But I think I found the way around it.  There is a `type` function that meets my needs.

`.type('boolean')`

**Comment by carlitux** [comment]
@nblasgen I updated the dependencies I think that will enable new checks
