### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by prescientmoon** [carlitux/koa-async-validator#3]
In the readme its stated express supports regex routes:

![image](https://user-images.githubusercontent.com/39400800/60770377-45c3f000-a0e3-11e9-92d5-de3959c714ad.png)

I think that should actually say 'koa-router allows you to define regex routes'!

**Comment by carlitux** [comment]
Thanks!

**Comment by carlitux** [comment]
closed by https://github.com/carlitux/koa-async-validator/pull/4
